services:
  postgres:
    image: postgres:16
    container_name: mensageria-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mensageria
      POSTGRES_USER: mensageria
      POSTGRES_PASSWORD: mensageria
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mensageria-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
